
export default {
    ADD_PROJECT: 'ADD_PROJECT',
    REMOVE_PROJECT: 'REMOVE_PROJECT',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DETAIL_PROJECT: 'DETAIL_PROJECT',
    RESET_SELECTED_PROJECT: 'RESET_SELECTED_PROJECT'
};